spring.application.name=cliente-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db_minimarket

#sdasdsad tuve q cambiar el username y el pass pq estoy usando mariadb
spring.datasource.username=nicolas
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
